---
apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  name: "{{ .Release.Name }}-app"
  annotations:
    volume.beta.kubernetes.io/storage-class: "application"
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "8Gi"
