---
apiVersion: "v1"
kind: "PersistentVolume"
metadata:
  name: "{{ .Release.Name }}-app"
  annotations:
    volume.alpha.kubernetes.io/storage-class: "default"
spec:
  capacity:
    storage: "10Gi"
  accessModes:
    - "ReadWriteOnce"
  persistentVolumeReclaimPolicy: "Retain"
  hostPath:
    path: {{ .Values.app.path | quote }}
