---
apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  labels:
    application: "apache2"
    role: "webserver"
  name: "webserver"
spec:
  replicas: 1
  selector:
    matchLabels:
      application: "apache2"
      role: "webserver"
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: "RollingUpdate"
  template:
    metadata:
      labels:
        application: "apache2"
        role: "webserver"
    spec:
      volumes:
        - name: "application"
          hostPath:
            path: {{ default "/mnt/development" .Values.hostPath | quote }}
      containers:
        - name: "apache2"
          # env:
          # - name: "FOO"
          #   value: "BAR"
          image: {{ default "quay.io/littlemanco/apache-php:f8eb259" .Values.container | quote }}
          imagePullPolicy: "IfNotPresent"
          # args:
          #   - "command"
          #   - "line"
          #   - "arguments"
          resources:
            limits:
              cpu: "100m"
              memory: "512Mi"
            requests:
              cpu: "100m"
              memory: "512Mi"
          securityContext:
            privileged: false
          ports:
            - containerPort: 80
              protocol: "TCP"
              name: "http"
          volumeMounts:
            - name: "application"
              mountPath: "/var/www"
          livenessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 1
            timeoutSeconds: 1
          readinessProbe:
            tcpSocket:
              port: "http"
            initialDelaySeconds: 1
            timeoutSeconds: 1
      restartPolicy: "Always"
      securityContext: {}
