---
apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  labels:
    application: "apache2"
    role: "webserver"
  name: "webserver"
spec:
  replicas: 1
  selector:
    matchLabels:
      application: "apache2"
      role: "webserver"
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: "RollingUpdate"
  template:
    metadata:
      labels:
        application: "apache2"
        role: "webserver"
    spec:
      # volumes:
      # - name: "webserver-etc-conf-d"
      # configMap:
      #   name: "webserver-etc-conf-d"
      # - name: "webserver-data"
      #   hostPath:
      #     path: /data/webserver/
      containers:
        - name: "apache2"
          # env:
          # - name: "FOO"
          #   value: "BAR"
          image: "quay.io/littlemanco/apache-php:f8eb259"
          imagePullPolicy: "IfNotPresent"
          # args:
          #   - "command"
          #   - "line"
          #   - "arguments"
          resources:
            limits:
              cpu: "100m"
              memory: "512Mi"
            requests:
              cpu: "100m"
              memory: "512Mi"
          securityContext:
            privileged: false
          ports:
            - containerPort: 80
              protocol: "TCP"
              name: "http"
          # volumeMounts:
          # - name: "webserver-etc-conf-d"
          #   readOnly: true
          #   mountPath: "/etc/webserver/conf.d"
          # - name: "webserver-data
          #   readOnly: false
          #   mountPath: "/data"
          livenessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 1
            timeoutSeconds: 1
          readinessProbe:
            tcpSocket:
              port: "http"
            initialDelaySeconds: 1
            timeoutSeconds: 1
      restartPolicy: "Always"
      securityContext: {}
