---
apiVersion: "v1"
kind: "PersistentVolume"
metadata:
  name: "{{ .Release.Name }}-mysql"
spec:
  capacity:
    storage: "10Gi"
  accessModes:
    - "ReadWriteOnce"
  persistentVolumeReclaimPolicy: "Retain"
  hostPath:
    path: {{ .Values.mysql.path | quote }}
